spring:
  application:
    name: fitCoin

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
            required: true
        debug: true

# MinIO ??
#minio:
#  endpoint: ${MINIO_URL}
#  public-endpoint: ${MINIO_PUBLIC_URL}
#  access-key: ${MINIO_ROOT_USER}
#  secret-key: ${MINIO_ROOT_PASSWORD}
#  bucket: ${MINIO_BUCKET}

# JWT ??
jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY}

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
  api-docs:
    path: /api/v3/api-docs

server:
  port: ${SERVER_PORT}

cors:
  allowed-origins:
    - ${CORS_ORIGIN_LOCAL_VITE:http://localhost:5173}
    - ${CORS_ORIGIN_LOCAL_REACT:http://localhost:3000}
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS

#  이메일 설정
email:
  code:
    expired-time: 300000   # 5분(ms) - 인증 코드 유효 시간
  token:
    expired-time: 1800000  # 30분(ms) - 이메일 인증 토큰 유효 시간