export const metadata = {
    title: 'Next.js App',
    description: 'Generated by shrew',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="ko">
            <body>{children}</body>
        </html>
    )
}
