networks:
  a504-network:
    external: true

services:
  nextjs_app:
    container_name: nextjs_app
    image: nextjs_app:latest
    env_file: ../Frontend/fitCoin/.env
    networks:
      - a504-network
    restart: always
