networks:
  a504-network:
    external: true

services:
  api-server:
    container_name: api-server
    image: api-server:latest
    env_file: ../Backend/fitCoin/.env
    networks:
      - a504-network
    restart: always
