events {}

http {
        upstream nextjs_app {
                server nextjs_app:3000;
        }
        upstream api-server {
                server api-server:8080; # 백엔드 컨테이너 이름
        }
        upstream minio-api {
                server minio:9000;
        }
        upstream minio-console {
                server minio:9001;
        }



        # http(80) -> https(443) 강제 리다이렉트
        server {
                listen 80;
                server_name j14a504.p.ssafy.io;
                return 301 https://$host$request_uri;
        }


        server {
                listen 443 ssl;
                server_name j14a504.p.ssafy.io;

                # SSL 인증서 경로
                ssl_certificate /etc/letsencrypt/live/j14a504.p.ssafy.io/fullchain.pem;
                ssl_certificate_key /etc/letsencrypt/live/j14a504.p.ssafy.io/privkey.pem;

                # 프론트엔드
                location / {
                        proxy_pass http://nextjs_app;
                        
                        proxy_set_header Host $host;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header X-Forwarded-Proto $scheme;
                }

                # API 서버
                location /api {
                        proxy_pass http://api-server;

                        proxy_set_header Host $host;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header X-Forwarded-Proto $scheme;
                }

                # MinIO S3 API (파일 업로드/다운로드)
                location /minio/ {
                        proxy_pass http://minio-api/;
                        proxy_set_header Host $host;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header X-Forwarded-Proto $scheme;

                        # 대용량 파일 업로드 대비
                        client_max_body_size 100M;
                        proxy_buffering off;
                        proxy_request_buffering off;
                }

                # MinIO 웹 콘솔
                location /minio-console/ {
                        proxy_pass http://minio-console/;
                        proxy_set_header Host $host;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header X-Forwarded-Proto $scheme;
                        proxy_set_header X-NginX-Proxy true;

                        # 콘솔 WebSocket 지원
                        proxy_http_version 1.1;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection "upgrade";
                }
        }
}