# 1. 의존성 설치 스테이지
FROM node:18-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY Frontend/fitCoin/package.json Frontend/fitCoin/package-lock.json* Frontend/fitCoin/yarn.lock* ./
RUN npm ci

# 2. 빌드 스테이지
FROM node:18-alpine AS builder
WORKDIR /app
COPY Frontend/fitCoin ./
COPY --from=deps /app/node_modules ./node_modules
RUN npm run build

# 3. 실행 스테이지
FROM node:18-alpine AS runner
WORKDIR /app

ENV NODE_ENV="production"
ENV NEXT_TELEMETRY_DISABLED="1"

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000
ENV PORT="3000"
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]